// const express = require('express');
// const bodyParser = require('body-parser');
// const { google } = require('googleapis');
// const axios = require('axios');
// require('dotenv').config(); // Load environment variables from .env file
// const { GoogleSpreadsheet } = require('google-spreadsheet')
// const { JWT } =  require('google-auth-library')
// const cors = require('cors');


// const app = express();
// const PORT = process.env.PORT || 3001;

// app.use(bodyParser.json());
// app.use(cors());

// app.post("/submit-form" , async(req, res)=>{


// const serviceAccountAuth = new JWT({
//   // env var values here are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   client_email: process.env.client_email,
//   private_key: process.env.private_key,
//   scopes: [
//     'https://www.googleapis.com/auth/spreadsheets'
//   ]
// });

// const doc = new GoogleSpreadsheet(process.env.spreadsheetId, serviceAccountAuth);

// await doc.loadInfo(); // loads document properties and worksheets
// console.log(doc.title);
// await doc.updateProperties({ title: 'Multiplayr Client EmailID' });

// const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
// console.log(sheet.title);


//     const HEADERS = ['Id', 'EmailID', 'Date']
//     await sheet.setHeaderRow(HEADERS)

//     const { email, time} = req.body

//     const values = [[email, time]];

//     await sheet.addRow(values)



//     let result = {
//         success: 'ok'
//     }

//     res.status(200).json(result)
// })



// // // Scopes for Google Sheets API
// // const SCOPES = ['https://www.googleapis.com/auth/spreadsheets'];



// // // Server start
// // app.post('/submit-form', async (req, res) => {
// //   const { email, time } = req.body;

// //   try {
// //     // Authorize the client with credentials and obtain a token
// //     const token = await authorize();
// //     oAuth2Client.setCredentials(token);

// //     await docs.loadInfo()

// //     // Add data to Google Sheets
// //     await addToGoogleSheet({ email, time });

// //     res.status(200).json({ message: 'Form submitted successfully' });
// //   } catch (error) {
// //     console.error('Error submitting form:', error.message);
// //     res.status(500).json({ error: 'Internal Server Error' });
// //   }
// // });

// // // Function to authorize the client with Google Sheets API
// // const authorize = async () => {
// //   try {
// //     const token = {}; // Implement logic to retrieve or refresh the token
// //     return token;
// //   } catch (error) {
// //     console.error('Authorization error:', error.message);
// //     throw error;
// //   }
// // };

// // // Function to add data to Google Sheets
// // const addToGoogleSheet = async ({ email, time }) => {
// //   try {
// //     // Authorize the client with credentials and obtain a token
// //     const token = await authorize();
// //     oAuth2Client.setCredentials(token);

// //     // Set up the Google Sheets API
// //     const sheets = google.sheets({ version: 'v4', auth: oAuth2Client });

// //     // Set your spreadsheetId and range
// //     const spreadsheetId = process.env.spreadsheetId;
// //     const range = 'Sheet1';

// //     // Data to be added
// //     const values = [[email, time]];

// //     // Append data to Google Sheets
// //     await sheets.spreadsheets.values.append({
// //       spreadsheetId,
// //       range,
// //       valueInputOption: 'USER_ENTERED',
// //       resource: { values },
// //     });

// //     console.log('Data added to Google Sheets successfully');
// //   } catch (error) {
// //     console.error('Error adding data to Google Sheets:', error.message);
// //     throw error;
// //   }
// // };

// app.listen(PORT, () => {
//   console.log(`Server is running on port ${PORT}`);
//   console.log(process.env.spreadsheetId);
// });
